name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin
        
      - name: Build Docker image
        run: docker build -t myapp .
      
      - name: Tag Docker Image
        run: docker tag myapp:latest bobcharlie/myapp:latest

      - name: Push Docker Image to DockerHub
        run: docker push bobcharlie/myapp:latest
